export const tools = [
  {
    id: 'figma',
    name: 'Figma / Figma Make',
    tagline: 'Design-to-code with AI generation',
    workflow: 2,
    workflowColor: '#ff2d55',
    iconBg: '#fff0f3',
    iconColor: '#ff2d55',
    tags: ['UI design', 'Prototyping', 'Design systems'],
    tagColor: { bg: '#fff0f3', text: '#c0185a' },
    skillDesign: 90,
    skillCoding: 25,
    skillColor: '#ff2d55',
    howItWorks: 'Figma is a browser-based design tool. Figma Make is its AI layer — describe a UI in natural language and it generates working React components or interactive prototypes directly inside Figma. Output can be exported as code.',
    yourProject: 'Guitar Practice Tracker — React + Tailwind, Apple-inspired design, 34 features including metronome, chord finder, recorder, and spaced repetition.',
    pros: [
      'No coding knowledge needed to get started',
      'Generates production-ready React + Tailwind code',
      'Instant visual feedback as you build',
      'Apple-quality design defaults out of the box',
    ],
    cons: [
      'Hosted on Figma\'s platform — less deploy control',
      'Harder to maintain long-term vs. a local codebase',
      'Complex logic can require manual code editing',
    ],
    pricing: 'Free tier available · Figma Make included in paid plans from $15/mo',
    whenToUse: 'When you have a clear visual idea and want to go from concept to working UI fast — especially for design-heavy apps where aesthetics matter as much as functionality.',
    whenToAvoid: 'When you need deep backend logic, complex state management, or a project you\'ll iterate on heavily over time.',
  },
  {
    id: 'replit',
    name: 'Replit',
    tagline: 'Browser-based coding + AI agent',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8faf4',
    iconColor: '#1d9e75',
    tags: ['Quick prototypes', 'No-setup coding', 'Instant deploy'],
    tagColor: { bg: '#e8faf4', text: '#0a6b4a' },
    skillDesign: 30,
    skillCoding: 35,
    skillColor: '#1d9e75',
    howItWorks: 'A cloud IDE that runs entirely in the browser — no local setup needed. Replit Agent lets you describe an app in plain English; it scaffolds, codes, debugs, and deploys for you. Hosts the app on Replit\'s own infrastructure automatically.',
    yourProject: null,
    pros: [
      'Zero local setup — works on any device with a browser',
      'Agent handles scaffolding, debugging, and deploy in one place',
      'Great for quick experiments and sharing prototypes',
      'Supports dozens of languages and frameworks',
    ],
    cons: [
      'Less control than a local dev environment',
      'Hosted on Replit infrastructure — not your own domain by default',
      'Can get expensive for always-on apps',
    ],
    pricing: 'Free tier available · Replit Core from $25/mo · Agent usage billed separately',
    whenToUse: 'When you want to spin up a working app fast without touching your local machine — demos, quick experiments, or sharing something with a non-technical collaborator.',
    whenToAvoid: 'When you need production-grade reliability, custom domains, or a codebase you\'ll maintain long-term with version control.',
  },
  {
    id: 'claude',
    name: 'Claude / Claude Code',
    tagline: 'AI pair programmer + agentic CLI coder',
    workflow: 1,
    workflowColor: '#007aff',
    iconBg: '#f0f4ff',
    iconColor: '#5856d6',
    tags: ['Code generation', 'Debugging', 'Refactoring'],
    tagColor: { bg: '#f0f0ff', text: '#3634a3' },
    skillDesign: 40,
    skillCoding: 50,
    skillColor: '#5856d6',
    howItWorks: 'Claude.ai is a chat interface for code generation, explanation, and review. Claude Code is a terminal agent that reads your codebase, plans changes, runs commands, and edits files autonomously — working alongside VS Code and your local tools.',
    yourProject: 'AI Updates dashboard (ai-updates-ten.vercel.app) — React/Vite app with on-demand RSS summarization, Apple-inspired design, mobile responsive.',
    pros: [
      'Understands full codebase context, not just snippets',
      'Claude Code edits files directly — no copy/paste',
      'Excellent at debugging complex multi-file issues',
      'Tight integration with your existing local workflow',
    ],
    cons: [
      'Requires a local dev environment (VS Code, Node, etc.)',
      'Claude Code uses API credits — costs add up on large projects',
      'Less visual/design-oriented than Figma Make',
    ],
    pricing: 'Claude.ai Pro $20/mo · Claude Code billed per API token usage',
    whenToUse: 'Your primary workflow. Best for projects you own end-to-end — building, debugging, refactoring, and deploying via GitHub + Vercel.',
    whenToAvoid: 'When you just need a quick throwaway prototype and don\'t want to set up a full local environment.',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'AI-native code editor (VS Code fork)',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f6ff',
    iconColor: '#378add',
    tags: ['Editor-centric', 'Codebase Q&A', 'Inline edits'],
    tagColor: { bg: '#eef5ff', text: '#0c4484' },
    skillDesign: 20,
    skillCoding: 60,
    skillColor: '#378add',
    howItWorks: 'A fork of VS Code with AI deeply embedded. Understands your entire codebase via embeddings, lets you chat with your repo, auto-completes multi-line edits, and applies AI suggestions inline. Uses Claude, GPT-4, and other models under the hood.',
    yourProject: null,
    pros: [
      'AI lives inside the editor — no context switching',
      'Codebase-aware: understands your whole project, not just open files',
      'Powerful tab autocomplete for multi-line edits',
      'Familiar VS Code interface — near-zero learning curve',
    ],
    cons: [
      'Another subscription on top of Claude/GitHub/Vercel',
      'Less capable as an autonomous agent vs. Claude Code',
      'Model quality depends on which underlying AI you select',
    ],
    pricing: 'Free tier (limited) · Pro $20/mo · Business $40/user/mo',
    whenToUse: 'If you want AI more deeply embedded in your editor experience and prefer typing in context over running a separate terminal agent.',
    whenToAvoid: 'If Claude Code already covers your needs — adding Cursor is largely redundant unless you specifically want the inline editor experience.',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    tagline: 'Deployment + hosting platform',
    workflow: 1,
    workflowColor: '#1d1d1f',
    iconBg: '#f5f5f7',
    iconColor: '#1d1d1f',
    tags: ['Deployment', 'Hosting', 'Preview URLs', 'Serverless'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 10,
    skillCoding: 30,
    skillColor: '#6e6e73',
    howItWorks: 'Connect a GitHub repo and Vercel auto-deploys every push. Handles CDN, serverless functions, environment variables, and preview URLs per branch. Optimized for React/Next.js but works with Vite, Svelte, and more.',
    yourProject: 'Hosts the AI Updates dashboard at ai-updates-ten.vercel.app — auto-deploys on every GitHub push.',
    pros: [
      'Zero-config deploys — push to GitHub, it\'s live',
      'Preview URLs for every branch — great for testing before merging',
      'Global CDN built in — fast everywhere',
      'Serverless functions for lightweight backend needs',
    ],
    cons: [
      'Not a coding tool — purely for deploy/host',
      'Free tier has usage limits; costs scale with traffic',
      'Vendor lock-in if you use Vercel-specific features heavily',
    ],
    pricing: 'Free hobby tier · Pro $20/mo · Enterprise custom pricing',
    whenToUse: 'Every time. This is the final step of Workflow 1 — the pipe that takes your GitHub code and puts it live on the internet automatically.',
    whenToAvoid: 'No real reason to avoid it for your use case. For very heavy backend workloads you\'d eventually move to a dedicated server, but that\'s far off.',
  },
  {
    id: 'github',
    name: 'GitHub',
    tagline: 'Version control + collaboration + CI/CD',
    workflow: 1,
    workflowColor: '#34c759',
    iconBg: '#eaf3de',
    iconColor: '#3b6d11',
    tags: ['Version control', 'History & rollback', 'Collaboration'],
    tagColor: { bg: '#eaf3de', text: '#2a5a0a' },
    skillDesign: 5,
    skillCoding: 40,
    skillColor: '#34c759',
    howItWorks: 'Cloud-hosted Git. Stores your code, tracks every change, and lets you roll back or branch freely. GitHub Actions can automate tests or builds. Vercel watches your repos and deploys on push. GitHub Copilot adds inline AI suggestions in editors.',
    yourProject: 'Source of truth for the AI Updates dashboard — every Claude Code edit gets committed and pushed here, triggering a Vercel deploy.',
    pros: [
      'Safety net for everything — roll back any mistake',
      'Branching lets you experiment without breaking production',
      'Vercel integration means deploy is automatic on push',
      'Free for public and private repos',
    ],
    cons: [
      'Git concepts (branches, commits, merge conflicts) have a learning curve',
      'Not a coding or deploy tool on its own — needs the rest of the stack',
    ],
    pricing: 'Free for individuals (unlimited private repos) · Teams $4/user/mo',
    whenToUse: 'Always — every project should be on GitHub from day one. It\'s the connective tissue between Claude Code and Vercel.',
    whenToAvoid: 'There\'s no good reason to avoid GitHub in your workflow. It\'s free and essential.',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    tagline: 'Open-source backend as a service',
    workflow: 2,
    workflowColor: '#1d9e75',
    iconBg: '#e8faf4',
    iconColor: '#1d9e75',
    tags: ['Auth & logins', 'Cloud database', 'Multi-user apps', 'Real-time sync'],
    tagColor: { bg: '#e8faf4', text: '#0a6b4a' },
    skillDesign: 5,
    skillCoding: 45,
    skillColor: '#1d9e75',
    howItWorks: 'Supabase gives you a full Postgres database, user authentication, file storage, and edge functions — all through a simple dashboard and JavaScript SDK. Connect it to your frontend and it handles backend plumbing: storing data, managing logins, and syncing across users.',
    yourProject: 'Powers the Guitar Practice Tracker backend — Postgres KV store, Hono edge functions, user auth with signup/login, per-user data storage, and migration from anonymous to authenticated accounts.',
    pros: [
      'Full Postgres database — far more powerful than simple key-value stores',
      'Auth system built in — email/password, OAuth, magic links out of the box',
      'Works with any frontend framework (React, Vue, vanilla JS)',
      'Open source — can self-host if needed',
      'Generous free tier for small projects',
    ],
    cons: [
      'More setup than a purely frontend-only app',
      'SQL/database concepts help but aren\'t required',
      'Edge functions require some backend comfort to configure',
    ],
    pricing: 'Free tier (2 projects, 500MB DB) · Pro $25/mo per project',
    whenToUse: 'Any time your app needs user accounts, data that persists across sessions, or multi-user support. Could be added to Workflow 1 (Claude Code + Vercel) just as easily as Workflow 2.',
    whenToAvoid: 'For purely static apps or single-user tools where data only lives in the browser — overkill if you don\'t need a backend.',
  },
  {
    id: 'geminicli',
    name: 'Gemini CLI',
    tagline: 'Open-source terminal AI agent by Google',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['Terminal agent', 'Code generation', 'Free tier'],
    tagColor: { bg: '#e8f4fb', text: '#0d47a1' },
    skillDesign: 10,
    skillCoding: 50,
    skillColor: '#1a73e8',
    howItWorks: 'An open-source AI agent that runs in your terminal, powered by Gemini 3. Reads your codebase, edits files, runs commands, and browses the web — all from natural language prompts. Direct alternative to Claude Code, with a generous free tier using just a Google account.',
    yourProject: null,
    pros: [
      'Completely free — 1,000 requests/day with a personal Google account',
      '1 million token context window holds large codebases in memory',
      'Built-in Google Search grounding for real-time web context',
      'Open source (Apache 2.0) — inspect and modify the code',
      'MCP support — compatible with same tooling as Claude Code',
    ],
    cons: [
      'Less polished than Claude Code for complex multi-file reasoning',
      'Newer and less battle-tested than Claude Code',
      'Free tier has daily limits — paid usage requires API key billing',
    ],
    pricing: 'Free — 1,000 req/day with Google account · Paid via Google AI Studio or Vertex AI key',
    whenToUse: 'When Claude Code token costs feel steep, for solo projects or smaller codebases, or when you want a free Claude Code alternative to experiment with.',
    whenToAvoid: 'When you need the most reliable multi-file agentic reasoning — Claude Code still has an edge on complex refactors and large production codebases.',
  },
  {
    id: 'stitch',
    name: 'Google Stitch',
    tagline: 'AI-native UI design platform by Google Labs',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['UI design', 'Vibe design', 'Prototyping', 'Free'],
    tagColor: { bg: '#e8f4fb', text: '#0d47a1' },
    skillDesign: 85,
    skillCoding: 15,
    skillColor: '#1a73e8',
    howItWorks: 'Describe a UI in plain English (or voice), and Stitch generates high-fidelity designs on an infinite canvas powered by Gemini. Exports to Figma, outputs HTML/CSS code, and stitches screens together into clickable prototypes. Launched by Google Labs in 2025, with a major platform update in March 2026.',
    yourProject: null,
    pros: [
      'Completely free with daily credit limits',
      'Voice canvas — speak changes directly to your design',
      'Exports directly to Figma for further refinement',
      'Infinite canvas with AI agent that reasons across your whole project',
      'Generates interactive prototypes by connecting screens',
    ],
    cons: [
      'HTML/CSS export only — no direct React or Vue output yet',
      'No animations or micro-interaction design',
      'Output quality varies — complex layouts need several iterations',
      'Experimental Google Labs product — long-term availability uncertain',
    ],
    pricing: 'Free with daily credit limits · stitch.withgoogle.com',
    whenToUse: 'Early-stage design exploration, rapid UI ideation, or when you want a free Figma Make alternative. Especially good for founders or PMs mocking up ideas before handing to developers.',
    whenToAvoid: 'When you need React component output, design system depth, or real-time team collaboration — Figma still wins for production design workflows.',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    tagline: 'AI-powered research and knowledge tool by Google',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['Research', 'Document Q&A', 'Audio overviews', 'Free'],
    tagColor: { bg: '#e8f4fb', text: '#0d47a1' },
    skillDesign: 5,
    skillCoding: 5,
    skillColor: '#1a73e8',
    howItWorks: 'Feed it documents, PDFs, URLs, or notes and chat with them directly. NotebookLM reads your sources and lets you ask questions, generate summaries, find connections across documents, and create Audio Overviews — a podcast-style summary of your material. Powered by Gemini.',
    yourProject: null,
    pros: [
      'Chat directly with your own documents — not general web knowledge',
      'Audio Overviews turn dense material into a listenable podcast',
      'Surfaces connections across multiple sources automatically',
      'Free to use with a Google account',
      'Great for onboarding teams to new topics quickly',
    ],
    cons: [
      'Limited to the sources you upload — no live web search by default',
      'Not a coding or building tool — purely for research and synthesis',
      'Document size and source limits apply on the free tier',
    ],
    pricing: 'Free with Google account · NotebookLM Plus via Google AI Pro ($19.99/mo)',
    whenToUse: 'When your team needs to get up to speed on a topic fast — drop in articles, reports, or docs and start asking questions. Great complement to the AI Updates dashboard.',
    whenToAvoid: 'When you need to build, code, or design something — this is a reading and research tool, not a production tool.',
  },
  {
    id: 'cowork',
    name: 'Cowork',
    tagline: 'Desktop automation tool for non-developers by Anthropic',
    workflow: null,
    workflowColor: null,
    iconBg: '#EEEDFE',
    iconColor: '#5856d6',
    tags: ['Automation', 'File management', 'No-code', 'Desktop'],
    tagColor: { bg: '#EEEDFE', text: '#3C3489' },
    skillDesign: 5,
    skillCoding: 5,
    skillColor: '#5856d6',
    howItWorks: 'A desktop app by Anthropic that lets non-developers automate file and task management using Claude. Describe what you want to do in plain English — move files, rename batches, process documents, organize folders — and Cowork handles it without any coding required.',
    yourProject: null,
    pros: [
      'No coding required — plain English instructions',
      'Powered by Claude — same AI as your coding workflow',
      'Great for non-technical team members to automate repetitive tasks',
      'Works with your local file system directly',
      'Bridges the gap between technical and non-technical teammates',
    ],
    cons: [
      'Desktop only — not a web or mobile tool',
      'Beta product — features and pricing still evolving',
      'Less suited for complex multi-step workflows vs. code-based automation',
    ],
    pricing: 'Available via Claude.ai — check anthropic.com for current pricing',
    whenToUse: 'When non-technical team members need to automate repetitive file or document tasks without asking a developer for help.',
    whenToAvoid: 'When you need complex logic, API integrations, or automation that touches systems beyond your local file system — use Claude Code instead.',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    tagline: 'App development platform by Google',
    workflow: null,
    workflowColor: null,
    iconBg: '#fff4e0',
    iconColor: '#f57c00',
    tags: ['Auth', 'Realtime database', 'Hosting', 'Cloud functions'],
    tagColor: { bg: '#fff4e0', text: '#e65100' },
    skillDesign: 5,
    skillCoding: 45,
    skillColor: '#f57c00',
    howItWorks: 'Google\'s all-in-one app backend — authentication, Firestore (NoSQL database), realtime database, cloud functions, hosting, and storage in one platform. Connect directly to your frontend via SDK. Well-suited for apps that need real-time data sync across devices.',
    yourProject: null,
    pros: [
      'Real-time data sync out of the box — great for live collaborative apps',
      'Tightly integrated with Google Cloud and other Google services',
      'Generous free Spark plan for small projects',
      'Mature, battle-tested platform with large community',
      'Authentication with 10+ providers built in',
    ],
    cons: [
      'NoSQL Firestore can be tricky to query for relational data',
      'Costs can escalate quickly at scale',
      'Vendor lock-in — migrating away from Firebase is painful',
      'Less SQL-friendly than Supabase for developers who know Postgres',
    ],
    pricing: 'Free Spark plan · Blaze pay-as-you-go plan based on usage',
    whenToUse: 'When you need real-time sync (chat, live collaboration, notifications) or are already in the Google ecosystem. Great for mobile apps via Flutter or React Native.',
    whenToAvoid: 'When your data is highly relational and SQL-based — Supabase is a better fit. Also avoid if vendor lock-in is a concern.',
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    tagline: 'Open-source backend server for web & mobile',
    workflow: null,
    workflowColor: null,
    iconBg: '#fdecea',
    iconColor: '#c0392b',
    tags: ['Open source', 'Auth', 'Database', 'Self-hostable'],
    tagColor: { bg: '#fdecea', text: '#922b21' },
    skillDesign: 5,
    skillCoding: 50,
    skillColor: '#c0392b',
    howItWorks: 'An open-source backend platform you can self-host or use via Appwrite Cloud. Provides auth, databases, storage, functions, and messaging through a clean REST and GraphQL API. Positioned as a self-hostable alternative to Firebase and Supabase with full data ownership.',
    yourProject: null,
    pros: [
      'Fully open source — self-host for complete data ownership',
      'Clean, consistent API across all services',
      'No vendor lock-in — your data stays yours',
      'Supports REST, GraphQL, and Realtime APIs',
      'Good free cloud tier for getting started',
    ],
    cons: [
      'Smaller community than Firebase or Supabase',
      'Self-hosting adds DevOps overhead',
      'Less mature ecosystem of third-party integrations',
      'Database is document-based, not Postgres SQL',
    ],
    pricing: 'Free cloud tier · Pro $15/mo · Self-hosted free (you pay for infra)',
    whenToUse: 'When data ownership and open-source flexibility matter most, or when you want a Firebase-like experience without Google lock-in.',
    whenToAvoid: 'When you need Postgres/SQL, a large ecosystem of integrations, or don\'t want to manage infrastructure.',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'AI chat assistant + coding helper by OpenAI',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f0f0',
    iconColor: '#1a1a1a',
    tags: ['Chat', 'Code gen', 'Deep Research', 'Image gen'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 30,
    skillCoding: 45,
    skillColor: '#1a1a1a',
    howItWorks: "OpenAI's flagship AI assistant. Powered by GPT-5.4, it handles code generation, debugging, data analysis, image creation, web search, and Deep Research. Canvas mode lets you iterate on code and documents side by side. The closest direct alternative to Claude.ai for general-purpose AI work.",
    yourProject: null,
    pros: [
      'Most widely used AI tool — huge community and resources',
      'GPT-5.4 has native computer use and unified coding',
      'Deep Research for synthesizing complex topics',
      'DALL·E image generation built in',
      'Free tier available with GPT-5 access (limited)',
    ],
    cons: [
      'Free tier has tight usage caps — hits limits quickly',
      'Less strong than Claude on nuanced writing and long-context reasoning',
      'Privacy: conversations used for training by default unless opted out',
      'Ads being rolled out on free tier in 2026',
    ],
    pricing: 'Free tier · Plus $20/mo · Pro $200/mo · Team $30/user/mo',
    whenToUse: 'When your team is already familiar with ChatGPT, or when you need image generation, Deep Research, or computer use built into one tool.',
    whenToAvoid: 'When you need the best long-context reasoning or nuanced writing — Claude has an edge there. Also avoid the free tier for sensitive work due to training data defaults.',
  },
  {
    id: 'codexcli',
    name: 'Codex CLI',
    tagline: "OpenAI's open-source terminal coding agent",
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f0f0',
    iconColor: '#1a1a1a',
    tags: ['CLI agent', 'Code gen', 'Open source', 'Mac/Linux'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 10,
    skillCoding: 55,
    skillColor: '#1a1a1a',
    howItWorks: "OpenAI's terminal coding agent — direct competitor to Claude Code and Gemini CLI. Built in Rust, runs locally, reads your codebase, edits files, and executes commands. Powered by GPT-5.4 and GPT-5.3-Codex models. Included with ChatGPT Plus/Pro/Business plans at no extra API cost.",
    yourProject: null,
    pros: [
      'Included free with ChatGPT Plus — no extra API token costs',
      'Subagents for parallelizing complex tasks',
      'Can attach screenshots and design specs as context',
      'MCP support — same tooling ecosystem as Claude Code',
      'Open source — inspect and contribute on GitHub',
    ],
    cons: [
      'Requires ChatGPT Plus ($20/mo) or API key to use',
      'Less battle-tested than Claude Code for complex refactors',
      'macOS/Linux only — Windows support is experimental',
      'Newer and smaller community than Claude Code',
    ],
    pricing: 'Included with ChatGPT Plus ($20/mo) · or via API key (usage-based)',
    whenToUse: "If you're already paying for ChatGPT Plus, this is essentially a free Claude Code alternative. Worth trying before paying Claude Code API costs.",
    whenToAvoid: "When you need the highest-quality multi-file reasoning — Claude Code still leads on complex production codebases.",
  },
  {
    id: 'v0',
    name: 'v0 by Vercel',
    tagline: 'AI-powered React/Next.js component generator',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f0f0',
    iconColor: '#1a1a1a',
    tags: ['UI generation', 'React', 'Next.js', 'One-click deploy'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 60,
    skillCoding: 30,
    skillColor: '#1a1a1a',
    howItWorks: 'Describe a UI in plain English and v0 generates production-ready React + Tailwind + shadcn/ui components instantly. Deploy to Vercel with one click. Import from Figma, sync to GitHub. Best-in-class for frontend component quality — the cleanest React output of any AI builder.',
    yourProject: null,
    pros: [
      'Cleanest React/Next.js component output of any AI tool',
      'One-click deploy to Vercel — no pipeline setup needed',
      'shadcn/ui + Tailwind output is production-grade',
      'Figma import on paid plans',
      'GitHub sync built in',
    ],
    cons: [
      'Frontend only — no backend, database, or auth',
      'Credit-based pricing can be unpredictable for iterative work',
      'Less useful outside the React/Next.js ecosystem',
      'No real-time collaboration on free/premium plans',
    ],
    pricing: 'Free ($5 credits/mo) · Premium $20/mo · Team $30/user/mo',
    whenToUse: 'When you need the fastest path to a polished React UI. Pair with Supabase for backend and you have a full stack without writing much code.',
    whenToAvoid: "When you need Vue, Svelte, or vanilla JS output, or when you need a full-stack app with auth and database built in — Supabase + Claude Code is a better fit.",
  },
  {
    id: 'lovable',
    name: 'Lovable',
    tagline: 'Full-stack AI app builder — frontend, backend, database',
    workflow: null,
    workflowColor: null,
    iconBg: '#fdecea',
    iconColor: '#e05c4b',
    tags: ['Full-stack', 'No-code', 'Supabase built-in', 'Instant deploy'],
    tagColor: { bg: '#fdecea', text: '#922b21' },
    skillDesign: 40,
    skillCoding: 10,
    skillColor: '#e05c4b',
    howItWorks: 'Describe your app in plain English and Lovable generates the complete stack — React frontend, Supabase backend, authentication, and database — all wired together and deployed instantly. GitHub sync and custom domains included. No local setup, no coding required. One of the fastest paths from idea to live app.',
    yourProject: null,
    pros: [
      'Generates full-stack apps — frontend + backend + auth in one prompt',
      'Supabase integration built in — no separate setup',
      'One-click deploy with GitHub sync',
      'Unlimited collaborators on Pro plan — great for teams',
      'No coding required — truly accessible to non-developers',
    ],
    cons: [
      'Credit-based pricing — complex apps and debugging burn credits fast',
      'Less control than a local codebase for complex custom logic',
      'Debugging within Lovable can be costly — better to export to GitHub',
      'Frontend design quality varies — may need polish in Figma',
    ],
    pricing: 'Free (30 credits/mo) · Starter $25/mo · Business $50/mo',
    whenToUse: 'When you need a working full-stack app fast — MVPs, client portals, internal tools — especially for non-technical team members who can\'t use Claude Code or Cursor.',
    whenToAvoid: 'When you need precise control over your codebase, complex custom backend logic, or are already comfortable with the Claude Code + Vercel + Supabase workflow.',
  },
  {
    id: 'framer',
    name: 'Framer',
    tagline: 'Visual website builder with AI layout generation',
    workflow: null,
    workflowColor: null,
    iconBg: '#f5f0ff',
    iconColor: '#6b21a8',
    tags: ['Visual design', 'AI layouts', 'CMS', 'Instant publish'],
    tagColor: { bg: '#f5f0ff', text: '#5b21b6' },
    skillDesign: 85,
    skillCoding: 15,
    skillColor: '#7c3aed',
    howItWorks: 'A Figma-like canvas that publishes directly as a live website — no developer handoff needed. Describe a layout in plain English and AI generates a full responsive page instantly. Built-in CMS, hosting, SEO, and analytics. Trusted by 500,000+ designers including teams at Miro and Perplexity.',
    yourProject: null,
    pros: [
      'Design and publish in the same tool — no handoff to developers',
      'AI generates full page layouts from text prompts',
      'Built-in CMS, hosting, analytics, and custom domains',
      'Best-in-class animations and micro-interactions without code',
      'Free plan available with generous limits',
    ],
    cons: [
      'Steep learning curve coming from Figma — different mental model',
      'Per-site pricing adds up if running multiple projects',
      'Not ideal for complex content-heavy sites or large blogs',
      'Extra editors can get expensive on higher plans',
    ],
    pricing: 'Free · Basic $10/mo · Pro $30/mo · Scale $100+/mo',
    whenToUse: 'When you want a polished, design-forward website published fast without a developer. Great for landing pages, portfolios, and marketing sites where visual quality matters most.',
    whenToAvoid: 'When you need complex web app functionality, user auth, or a database — use Lovable or the Claude Code + Supabase workflow instead.',
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    tagline: 'Browser-based full-stack AI app builder by StackBlitz',
    workflow: null,
    workflowColor: null,
    iconBg: '#fff8e8',
    iconColor: '#b45309',
    tags: ['Full-stack', 'Browser-based', 'No install', 'React/Vite'],
    tagColor: { bg: '#fff8e8', text: '#92400e' },
    skillDesign: 35,
    skillCoding: 15,
    skillColor: '#d97706',
    howItWorks: 'Describe an app in plain English and Bolt generates a full React + Tailwind frontend with backend, database, auth, and hosting — all running in your browser via WebContainers (no local install needed). Bolt V2 added Bolt Cloud with built-in databases, hosting, and analytics. Uses Claude as its default AI model.',
    yourProject: null,
    pros: [
      'Zero install — runs entirely in the browser via WebContainers',
      'Generates full stack including database, auth, and hosting',
      'Figma import — drop designs directly into chat',
      'Token rollover — unused tokens carry to next month',
      'Powers 1M+ websites via Netlify partnership',
    ],
    cons: [
      'Token-based pricing is unpredictable — debugging burns tokens fast',
      'Complex apps (15+ components) degrade in quality',
      'Teams pricing is per-user — gets expensive vs Lovable',
      'Less design polish than Lovable on the frontend',
    ],
    pricing: 'Free (1M tokens/mo) · Pro $25/mo · Teams $30/user/mo',
    whenToUse: 'When you want Lovable-style full-stack generation but prefer token-based pricing or need Figma import. Good for solo builders who want maximum tokens for the price.',
    whenToAvoid: 'For teams — Lovable\'s flat $25/mo covers unlimited users vs $30/user on Bolt. Also avoid for enterprise-grade apps where complex logic and security are critical.',
  },
]

export const workflows = [
  {
    id: 1,
    label: 'Workflow 1 — current stack',
    subtitle: 'AI Updates dashboard · local dev · GitHub deploy',
    color: '#007aff',
    project: 'AI Updates dashboard (ai-updates-ten.vercel.app) — React/Vite app with on-demand RSS summarization, Apple-inspired design, mobile responsive.',
    steps: [
      { name: 'Claude.ai', role: 'Ideate & generate', iconBg: '#f0f4ff', icon: 'claude' },
      { name: 'Claude Code', role: 'Edit & build locally', iconBg: '#f0f4ff', icon: 'claudecode' },
      { name: 'GitHub', role: 'Commit & version', iconBg: '#eaf3de', icon: 'github' },
      { name: 'Vercel', role: 'Deploy & host', iconBg: '#f5f5f7', icon: 'vercel' },
    ],
  },
  {
    id: 2,
    label: 'Workflow 2 — Figma Make + Supabase',
    subtitle: 'Guitar Practice Tracker · browser-based · cloud backend',
    color: '#ff2d55',
    project: 'Guitar Practice Tracker — React + Tailwind, Apple-inspired design, 34 features including metronome, chord finder, recorder, and spaced repetition.',
    steps: [
      { name: 'Figma Make', role: 'Design & build UI', iconBg: '#fff0f3', icon: 'figma' },
      { name: 'React + Tailwind', role: 'Generated code', iconBg: '#e8faf4', icon: 'react' },
      { name: 'Supabase', role: 'Auth & cloud data', iconBg: '#e8faf4', icon: 'supabase' },
      { name: 'Figma hosted', role: 'Live in browser', iconBg: '#fff0f3', icon: 'web' },
    ],
  },
]
