export const tools = [
  {
    id: 'figma',
    name: 'Figma / Figma Make',
    tagline: 'Design-to-code with AI generation',
    workflow: 2,
    workflowColor: '#ff2d55',
    iconBg: '#fff0f3',
    iconColor: '#ff2d55',
    tags: ['UI design', 'Prototyping', 'Design systems'],
    tagColor: { bg: '#fff0f3', text: '#c0185a' },
    skillDesign: 90,
    skillCoding: 25,
    skillColor: '#ff2d55',
    howItWorks: 'Figma is the industry-standard browser-based design tool. Figma Make is its AI layer — describe a UI in natural language and it generates working React components or interactive prototypes directly inside Figma. Output can be exported as code. Figma also now includes an MCP server that lets AI coding tools like Claude Code and Cursor read your Figma layouts and generate code that matches your design system.',
    yourProject: 'Guitar Practice Tracker — React + Tailwind, Apple-inspired design, 34 features including metronome, chord finder, recorder, and spaced repetition.',
    pros: [
      'No coding knowledge needed to get started',
      'Generates production-ready React + Tailwind code',
      'Instant visual feedback as you build',
      'New MCP server lets Claude Code and Cursor read your Figma designs directly',
    ],
    cons: [
      'AI credits now strictly enforced since March 18, 2026 — heavy AI use can hit limits',
      'Seat-based pricing model is complex; wrong seat type can waste money',
      'Hosted on Figma\'s platform — less deploy control than a local codebase',
    ],
    pricing: 'Free (Starter) · Professional $16/editor/mo · Organization $55/editor/mo · Enterprise $90/editor/mo — Figma Make included in paid plans; AI credits bundled',
    whenToUse: 'When you have a clear visual idea and want to go from concept to working UI fast — especially for design-heavy apps where aesthetics matter as much as functionality.',
    whenToAvoid: 'When you need deep backend logic, complex state management, or a project you\'ll iterate on heavily over time.',
  },
  {
    id: 'replit',
    name: 'Replit',
    tagline: 'Browser-based coding + AI agent',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8faf4',
    iconColor: '#1d9e75',
    tags: ['Quick prototypes', 'No-setup coding', 'Instant deploy'],
    tagColor: { bg: '#e8faf4', text: '#0a6b4a' },
    skillDesign: 30,
    skillCoding: 35,
    skillColor: '#1d9e75',
    howItWorks: 'A cloud IDE that runs entirely in the browser — no local setup needed. Replit Agent (now Agent 3) lets you describe an app in plain English; it scaffolds, codes, debugs, and deploys for you. Hosts the app on Replit\'s own infrastructure automatically. In February 2026 Replit overhauled its pricing: Core dropped to $20/mo and a new Pro plan replaced the old Teams tier.',
    yourProject: null,
    pros: [
      'Zero local setup — works on any device with a browser',
      'Agent 3 handles scaffolding, debugging, and deploy in one place',
      'Core plan now just $20/mo (down from $25) with up to 5 collaborators',
      'New Pro plan ($100/mo) supports up to 15 builders with pooled credits',
    ],
    cons: [
      'Effort-based credit pricing is unpredictable — Agent use can drain credits fast',
      'Always-on deployments add costs beyond your base subscription',
      'Less control than a local dev environment; not ideal for production-grade apps',
    ],
    pricing: 'Free (Starter) · Core $20/mo · Pro $100/mo (up to 15 builders) · Enterprise custom — credits for AI usage billed on top',
    whenToUse: 'When you want to spin up a working app fast without touching your local machine — demos, quick experiments, or sharing something with a non-technical collaborator.',
    whenToAvoid: 'When you need production-grade reliability, predictable costs, or a codebase you\'ll maintain long-term with version control.',
  },
  {
    id: 'claude',
    name: 'Claude / Claude Code',
    tagline: 'One of the top-ranked vibe coding tools of 2026 — chat + agentic coder',
    workflow: 1,
    workflowColor: '#007aff',
    iconBg: '#f0f4ff',
    iconColor: '#5856d6',
    tags: ['Code generation', 'Debugging', 'Refactoring'],
    tagColor: { bg: '#f0f0ff', text: '#3634a3' },
    skillDesign: 40,
    skillCoding: 50,
    skillColor: '#5856d6',
    howItWorks: 'Claude.ai is a chat interface for code generation, explanation, and planning. Claude Code is an agentic coding tool that reads your entire codebase, plans changes, runs commands, and edits files autonomously. Available as a terminal agent, a VS Code extension, and via the Claude.ai web interface. Consistently ranked in the top 2–3 vibe coding tools of 2026 alongside Cursor and Devin Desktop.',
    yourProject: 'AI Updates dashboard (ai-updates-ten.vercel.app) — React/Vite app with on-demand RSS summarization, Apple-inspired design, mobile responsive.',
    pros: [
      'Understands full codebase context with a 1M token context window',
      'Claude Code edits files directly — no copy/paste',
      'Pro plan ($20/mo) includes Claude Code access; Max plans for heavy users',
      'Current model line is Fable 5, Opus 5, Sonnet 5, and Haiku 4.5 — pick cost against task difficulty',
      'Available as terminal agent, VS Code extension, and web interface — flexible to your workflow',
    ],
    cons: [
      'Heavy Claude Code use can exhaust Pro plan limits — Max 5x ($100/mo) or 20x ($200/mo) needed for professional daily use',
      'Less visual/design-oriented than Figma Make',
    ],
    pricing: 'Claude.ai Pro $20/mo (includes Claude Code) · Max 5x $100/mo · Max 20x $200/mo · API per MTok in/out: Haiku 4.5 $1/$5 · Sonnet 5 $2/$10 (introductory, rising to $3/$15 after 31 Aug 2026) · Opus 5 $5/$25 · Fable 5 $10/$50 — cache hits 10% of input, Batch API 50% off',
    whenToUse: 'Your primary workflow. Best for projects you own end-to-end — building, debugging, refactoring, and deploying via GitHub + Vercel.',
    whenToAvoid: 'When you just need a quick throwaway prototype and don\'t want to set up a full local environment.',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'AI-native code editor (VS Code fork)',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f6ff',
    iconColor: '#378add',
    tags: ['Editor-centric', 'Codebase Q&A', 'Background agents'],
    tagColor: { bg: '#eef5ff', text: '#0c4484' },
    skillDesign: 20,
    skillCoding: 60,
    skillColor: '#378add',
    howItWorks: 'A fork of VS Code with AI deeply embedded. Understands your entire codebase via embeddings, lets you chat with your repo, auto-completes multi-line edits, and applies AI suggestions inline. Background Agents (launched early 2026) let you run up to 8 parallel agents working on different parts of your codebase while you stay focused elsewhere. Composer 2.5, released 18 May 2026 on a Kimi K2.5 base, is Cursor\'s own agent model — it matches Opus 4.7 on key agent benchmarks at roughly a tenth of the cost. Cursor crossed $2B ARR in February 2026 and is now used by half of Fortune 500 companies.',
    yourProject: null,
    pros: [
      'AI lives inside the editor — no context switching',
      'Background Agents run autonomously up to 8 at once while you work',
      'Composer 2.5 makes heavy agent use genuinely cheap — frontier-class results at ~1/10 the cost',
      'Supermaven autocomplete (acquired 2025) is best-in-class multi-line prediction',
      'Familiar VS Code interface — near-zero learning curve',
    ],
    cons: [
      'Credit-based billing still confuses — usage now splits into separate pools for first-party Composer models and third-party APIs',
      'Six tiers plus a new Premium team seat make cost modelling a chore before you commit a team',
      'Less capable as an autonomous terminal agent vs. Claude Code',
      'Another subscription on top of Claude — redundant if Claude Code covers your needs',
    ],
    pricing: 'Free (Hobby) · Pro $20/mo · Pro+ $60/mo · Ultra $200/mo · Teams $40/user/mo · Premium seat $120/mo ($96 annual, added June 2026, 5x Standard usage) · Enterprise custom — overages at API rates',
    whenToUse: 'If you want AI more deeply embedded in your editor experience and prefer typing in context over running a separate terminal agent. Background Agents are compelling for multi-file refactors.',
    whenToAvoid: 'If Claude Code already covers your needs — adding Cursor is largely redundant unless you specifically want the inline editor and background agent experience.',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    tagline: 'Deployment + hosting platform',
    workflow: 1,
    workflowColor: '#1d1d1f',
    iconBg: '#f5f5f7',
    iconColor: '#1d1d1f',
    tags: ['Deployment', 'Hosting', 'Preview URLs', 'Serverless'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 10,
    skillCoding: 30,
    skillColor: '#6e6e73',
    howItWorks: 'Connect a GitHub repo and Vercel auto-deploys every push. Handles CDN, serverless functions, environment variables, and preview URLs per branch. Optimized for React/Next.js but works with Vite, Svelte, and more. February 2026 Pro plan update brought Turbo build machines (30 vCPUs), unlimited free viewer seats, and faster no-queue builds.',
    yourProject: 'Hosts the AI Updates dashboard at ai-updates-ten.vercel.app — auto-deploys on every GitHub push.',
    pros: [
      'Zero-config deploys — push to GitHub, it\'s live',
      'Preview URLs for every branch — great for testing before merging',
      'February 2026 Pro update: Turbo builds, unlimited viewers, 10M edge requests included',
      'Seamless v0 integration for generating React UI components',
    ],
    cons: [
      'Not a coding tool — purely for deploy/host',
      'Usage-based billing kicks in above included limits (bandwidth, functions)',
      'Vendor lock-in if you use Vercel-specific features heavily',
    ],
    pricing: 'Free Hobby tier · Pro $20/mo (includes $20 usage credit, 1TB bandwidth) · Enterprise custom pricing',
    whenToUse: 'Every time. This is the final step of Workflow 1 — the pipe that takes your GitHub code and puts it live on the internet automatically.',
    whenToAvoid: 'No real reason to avoid it for your use case. For very heavy backend workloads you\'d eventually move to a dedicated server, but that\'s far off.',
  },
  {
    id: 'github',
    name: 'GitHub',
    tagline: 'Version control + collaboration + CI/CD',
    workflow: 1,
    workflowColor: '#34c759',
    iconBg: '#eaf3de',
    iconColor: '#3b6d11',
    tags: ['Version control', 'History & rollback', 'Collaboration'],
    tagColor: { bg: '#eaf3de', text: '#2a5a0a' },
    skillDesign: 5,
    skillCoding: 40,
    skillColor: '#34c759',
    howItWorks: 'Cloud-hosted Git. Stores your code, tracks every change, and lets you roll back or branch freely. GitHub Actions can automate tests or builds. Vercel watches your repos and deploys on push. GitHub Copilot moved to usage-based AI Credits on 1 June 2026, with inline completions free on all paid plans.',
    yourProject: 'Source of truth for the AI Updates dashboard — every Claude Code edit gets committed and pushed here, triggering a Vercel deploy.',
    pros: [
      'Safety net for everything — roll back any mistake',
      'Branching lets you experiment without breaking production',
      'Vercel integration means deploy is automatic on push',
      'GitHub Copilot has a free tier, and inline completions cost nothing on paid plans',
    ],
    cons: [
      'Git concepts (branches, commits, merge conflicts) have a learning curve',
      'Not a coding or deploy tool on its own — needs the rest of the stack',
    ],
    pricing: 'Free for individuals (unlimited private repos) · Teams $4/user/mo · Copilot Pro add-on $10/mo · Copilot Pro+ $39/mo',
    whenToUse: 'Always — every project should be on GitHub from day one. It\'s the connective tissue between Claude Code and Vercel.',
    whenToAvoid: 'There\'s no good reason to avoid GitHub in your workflow. It\'s free and essential.',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    tagline: 'Open-source backend as a service',
    workflow: 2,
    workflowColor: '#1d9e75',
    iconBg: '#e8faf4',
    iconColor: '#1d9e75',
    tags: ['Auth & logins', 'Cloud database', 'Multi-user apps', 'Real-time sync'],
    tagColor: { bg: '#e8faf4', text: '#0a6b4a' },
    skillDesign: 5,
    skillCoding: 45,
    skillColor: '#1d9e75',
    howItWorks: 'Supabase gives you a full Postgres database, user authentication, file storage, and edge functions — all through a simple dashboard and JavaScript SDK. Connect it to your frontend and it handles backend plumbing: storing data, managing logins, and syncing across users. Pricing is now Free, Pro ($25/mo), Team ($599/mo), and Enterprise — the Team plan replaced the old "Business" tier.',
    yourProject: 'Powers the Guitar Practice Tracker backend — Postgres database, user auth with signup/login, per-user data storage.',
    pros: [
      'Full Postgres database — far more powerful than simple key-value stores',
      'Auth system built in — email/password, OAuth, magic links out of the box',
      'Works with any frontend framework (React, Vue, vanilla JS)',
      'Pro plan at $25/mo remains the best-value managed Postgres+auth combo',
    ],
    cons: [
      'Usage-based overages on bandwidth, storage, and compute can surprise you at scale',
      'Free tier pauses projects after 1 week of inactivity — not production-ready',
      'Team plan jumps steeply to $599/mo — a big gap from Pro',
    ],
    pricing: 'Free (2 projects, 500MB DB, pauses after 7 days inactive) · Pro $25/mo per project · Team $599/mo · Enterprise custom',
    whenToUse: 'Any time your app needs user accounts, data that persists across sessions, or multi-user support.',
    whenToAvoid: 'For purely static apps or single-user tools where data only lives in the browser — overkill if you don\'t need a backend.',
  },
  {
    id: 'geminicli',
    name: 'Antigravity CLI (replaced Gemini CLI)',
    tagline: "Google's terminal agent — Gemini CLI retired June 2026",
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['Terminal agent', 'Parallel agents', 'Code generation'],
    tagColor: { bg: '#e8f4fb', text: '#0d47a1' },
    skillDesign: 10,
    skillCoding: 50,
    skillColor: '#1a73e8',
    howItWorks: 'At I/O on 19 May 2026 Google consolidated its developer tooling under the Antigravity brand. Gemini CLI and the Gemini Code Assist IDE extensions stopped serving consumer requests on 18 June 2026 — free, AI Pro, and Ultra users all lost access; Gemini Code Assist Standard and Enterprise licences kept theirs. Antigravity CLI is the successor: built in Go, it reads your codebase, edits files, and runs commands from the terminal, and adds an orchestrator that spawns dynamic subagents with isolated context to run subtasks in parallel. Agent Skills, Hooks, Subagents, and Extensions carry over as Antigravity plugins. Sessions can be exported to the Antigravity GUI.',
    yourProject: null,
    pros: [
      'Parallel subagents let large refactors run in the background without blocking the terminal',
      'Persistent history — context survives between sessions',
      'Large context window holds sizeable codebases in memory',
      'Snappier than Gemini CLI and works well over remote SSH',
      'Plugins preserve the Gemini CLI extension ecosystem',
    ],
    cons: [
      'Google retired Gemini CLI for consumers on short notice — a real signal about tooling stability',
      'Still less polished than Claude Code for complex multi-file reasoning',
      'The generous Gemini-account free tier no longer applies in the same form — check current limits',
    ],
    pricing: 'Check current terms — access moved with the Antigravity transition. Enterprise customers on Gemini Code Assist Standard or Enterprise retain their existing entitlement.',
    whenToUse: 'When you want parallel agent orchestration from the terminal, or you are already inside the Google Cloud ecosystem.',
    whenToAvoid: 'When you need the most reliable multi-file agentic reasoning — Claude Code still has an edge on complex refactors and large production codebases. Also think twice if you want a tool that will still exist under the same name in a year.',
  },
  {
    id: 'stitch',
    name: 'Google Stitch',
    tagline: 'AI-native UI design platform by Google Labs',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['UI design', 'Vibe design', 'Prototyping', 'Free'],
    tagColor: { bg: '#e8f4fb', text: '#0d47a1' },
    skillDesign: 85,
    skillCoding: 15,
    skillColor: '#1a73e8',
    howItWorks: 'Describe a UI in plain English (or voice), and Stitch generates high-fidelity designs on an infinite canvas powered by Gemini. Exports to Figma, outputs HTML/CSS code, and stitches screens together into clickable prototypes. Launched by Google Labs in 2025 with a major platform update in March 2026. Still a Google Labs experiment — long-term availability not guaranteed.',
    yourProject: null,
    pros: [
      'Completely free with daily credit limits',
      'Voice canvas — speak changes directly to your design',
      'Exports directly to Figma for further refinement',
      'Generates interactive prototypes by connecting screens',
    ],
    cons: [
      'HTML/CSS export only — no direct React or Vue output yet',
      'No animations or micro-interaction design',
      'Output quality varies — complex layouts need several iterations',
      'Experimental Google Labs product — long-term availability uncertain',
    ],
    pricing: 'Free with daily credit limits · stitch.withgoogle.com',
    whenToUse: 'Early-stage design exploration, rapid UI ideation, or when you want a free Figma Make alternative. Especially good for founders or PMs mocking up ideas before handing to developers.',
    whenToAvoid: 'When you need React component output, design system depth, or real-time team collaboration — Figma still wins for production design workflows.',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    tagline: 'AI-powered research and knowledge tool by Google',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['Research', 'Document Q&A', 'Audio overviews', 'Free'],
    tagColor: { bg: '#e8f4fb', text: '#0d47a1' },
    skillDesign: 5,
    skillCoding: 5,
    skillColor: '#1a73e8',
    howItWorks: 'Feed it documents, PDFs, URLs, or notes and chat with them directly. NotebookLM reads your sources and lets you ask questions, generate summaries, find connections across documents, and create Audio Overviews — a podcast-style summary of your material. Powered by Gemini 3. NotebookLM Plus (via Google AI Pro) gives 5x more Audio Overviews and higher usage limits.',
    yourProject: null,
    pros: [
      'Chat directly with your own documents — not general web knowledge',
      'Audio Overviews turn dense material into a listenable podcast',
      'Surfaces connections across multiple sources automatically',
      'Free to use with a Google account; upgraded limits with Google AI Pro',
    ],
    cons: [
      'Limited to the sources you upload — no live web search by default',
      'Not a coding or building tool — purely for research and synthesis',
      'Document size and source limits apply on the free tier',
    ],
    pricing: 'Free with Google account · NotebookLM Plus via Google AI Pro ($19.99/mo)',
    whenToUse: 'When your team needs to get up to speed on a topic fast — drop in articles, reports, or docs and start asking questions. Great complement to the AI Updates dashboard.',
    whenToAvoid: 'When you need to build, code, or design something — this is a reading and research tool, not a production tool.',
  },
  {
    id: 'cowork',
    name: 'Cowork',
    tagline: 'Desktop automation tool for non-developers by Anthropic',
    workflow: null,
    workflowColor: null,
    iconBg: '#EEEDFE',
    iconColor: '#5856d6',
    tags: ['Automation', 'File management', 'No-code', 'Desktop'],
    tagColor: { bg: '#EEEDFE', text: '#3C3489' },
    skillDesign: 5,
    skillCoding: 5,
    skillColor: '#5856d6',
    howItWorks: 'A desktop app by Anthropic that lets non-developers automate file and task management using Claude. Describe what you want to do in plain English — move files, rename batches, process documents, organize folders — and Cowork handles it without any coding required. Part of the growing Claude product ecosystem alongside Claude Code and the Claude web interface.',
    yourProject: null,
    pros: [
      'No coding required — plain English instructions',
      'Powered by Claude — same AI as your coding workflow',
      'Great for non-technical team members to automate repetitive tasks',
      'Works with your local file system directly',
    ],
    cons: [
      'Desktop only — not a web or mobile tool',
      'Beta product — features and pricing still evolving',
      'Less suited for complex multi-step workflows vs. code-based automation',
    ],
    pricing: 'Available via Claude plans — check anthropic.com for current pricing',
    whenToUse: 'When non-technical team members need to automate repetitive file or document tasks without asking a developer for help.',
    whenToAvoid: 'When you need complex logic, API integrations, or automation that touches systems beyond your local file system — use Claude Code instead.',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    tagline: 'App development platform by Google',
    workflow: null,
    workflowColor: null,
    iconBg: '#fff4e0',
    iconColor: '#f57c00',
    tags: ['Auth', 'Realtime database', 'Hosting', 'Cloud functions'],
    tagColor: { bg: '#fff4e0', text: '#e65100' },
    skillDesign: 5,
    skillCoding: 45,
    skillColor: '#f57c00',
    howItWorks: 'Google\'s all-in-one app backend — authentication, Firestore (NoSQL database), realtime database, cloud functions, hosting, and storage in one platform. Connect directly to your frontend via SDK. Well-suited for apps that need real-time data sync across devices.',
    yourProject: null,
    pros: [
      'Real-time data sync out of the box — great for live collaborative apps',
      'Tightly integrated with Google Cloud and other Google services',
      'Generous free Spark plan for small projects',
      'Mature, battle-tested platform with large community',
    ],
    cons: [
      'NoSQL Firestore can be tricky to query for relational data',
      'Costs can escalate quickly at scale',
      'Vendor lock-in — migrating away from Firebase is painful',
      'Less SQL-friendly than Supabase for developers who know Postgres',
    ],
    pricing: 'Free Spark plan · Blaze pay-as-you-go plan based on usage',
    whenToUse: 'When you need real-time sync (chat, live collaboration, notifications) or are already in the Google ecosystem. Great for mobile apps via Flutter or React Native.',
    whenToAvoid: 'When your data is highly relational and SQL-based — Supabase is a better fit. Also avoid if vendor lock-in is a concern.',
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    tagline: 'Open-source backend server for web & mobile',
    workflow: null,
    workflowColor: null,
    iconBg: '#fdecea',
    iconColor: '#c0392b',
    tags: ['Open source', 'Auth', 'Database', 'Self-hostable'],
    tagColor: { bg: '#fdecea', text: '#922b21' },
    skillDesign: 5,
    skillCoding: 50,
    skillColor: '#c0392b',
    howItWorks: 'An open-source backend platform you can self-host or use via Appwrite Cloud. Provides auth, databases, storage, functions, and messaging through a clean REST and GraphQL API. Positioned as a self-hostable alternative to Firebase and Supabase with full data ownership.',
    yourProject: null,
    pros: [
      'Fully open source — self-host for complete data ownership',
      'Clean, consistent API across all services',
      'No vendor lock-in — your data stays yours',
      'Supports REST, GraphQL, and Realtime APIs',
    ],
    cons: [
      'Smaller community than Firebase or Supabase',
      'Self-hosting adds DevOps overhead',
      'Less mature ecosystem of third-party integrations',
      'Database is document-based, not Postgres SQL',
    ],
    pricing: 'Free cloud tier · Pro $15/mo · Self-hosted free (you pay for infra)',
    whenToUse: 'When data ownership and open-source flexibility matter most, or when you want a Firebase-like experience without Google lock-in.',
    whenToAvoid: 'When you need Postgres/SQL, a large ecosystem of integrations, or don\'t want to manage infrastructure.',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'AI chat assistant + autonomous coding agent by OpenAI',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f0f0',
    iconColor: '#1a1a1a',
    tags: ['Chat', 'Code gen', 'Deep Research', 'Codex agent'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 30,
    skillCoding: 45,
    skillColor: '#1a1a1a',
    howItWorks: 'OpenAI\'s flagship AI assistant. Powered by GPT-5.4, it handles code generation, debugging, data analysis, image creation, web search, and Deep Research. Now includes Codex — an autonomous coding agent that can take on multi-file tasks in the cloud. Canvas mode lets you iterate on code and documents side by side. A new $8/mo "Go" tier launched in 2025 for budget-conscious users, though it includes ads.',
    yourProject: null,
    pros: [
      'Most widely used AI tool — huge community and resources',
      'Codex agent (included from Plus up) handles autonomous cloud coding tasks',
      'Deep Research synthesizes complex topics across dozens of sources',
      'DALL·E image generation + Sora video access on Plus and above',
    ],
    cons: [
      'Free and Go tiers now include ads (rolled out February 2026 in the US)',
      'Less strong than Claude on nuanced writing and long-context reasoning',
      'Codex credit pricing moved to token-based (April 2, 2026) — costs harder to predict',
    ],
    pricing: 'Free (ads in US) · Go $8/mo (ads) · Plus $20/mo · Pro $200/mo · Business $25/user/mo · Enterprise custom',
    whenToUse: 'When your team is already familiar with ChatGPT, or when you need image generation, Deep Research, Codex cloud agents, or Sora video in one tool.',
    whenToAvoid: 'When you need the best long-context reasoning or nuanced writing — Claude has an edge there. Also avoid Free/Go tiers for professional work due to ads and tight usage limits.',
  },
  {
    id: 'codexcli',
    name: 'Codex CLI',
    tagline: "OpenAI's open-source terminal coding agent",
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f0f0',
    iconColor: '#1a1a1a',
    tags: ['CLI agent', 'Code gen', 'Open source', 'Mac/Linux'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 10,
    skillCoding: 55,
    skillColor: '#1a1a1a',
    howItWorks: 'OpenAI\'s terminal coding agent — direct competitor to Claude Code and Antigravity CLI. Open source, runs locally, reads your codebase, edits files, and executes commands. There is also Codex cloud, which runs tasks in an isolated sandbox preloaded with your GitHub repo and returns a pull request, and a desktop app for managing several agents at once. Model line moves fast: GPT-5.3-Codex shipped February 2026, GPT-5.5 in April, and the GPT-5.6 family (Sol, Terra, Luna) by July. Included with ChatGPT Plus/Pro/Business plans; usage draws from your plan\'s pool. Codex moved to token-based billing on 2 April 2026.',
    yourProject: null,
    pros: [
      'Included with ChatGPT Plus ($20/mo) — no extra API token costs',
      'Codex cloud runs tasks async in a sandbox and returns a PR — review before anything merges',
      'Supports parallel subagents for complex tasks',
      'Can attach screenshots and design specs as context',
      'MCP support — same tooling ecosystem as Claude Code',
    ],
    cons: [
      'Requires ChatGPT Plus ($20/mo) or API key to use',
      'Token-based pricing since April 2026 makes cost less predictable',
      'Model churn is relentless — GPT-5.4 and 5.4 mini leave Codex for ChatGPT users on 31 August 2026, so pin your assumptions to a model, not to "Codex"',
      'Less battle-tested than Claude Code for complex refactors',
      'macOS/Linux primary; Windows support improving but not fully on par',
    ],
    pricing: 'Included with ChatGPT Plus ($20/mo) and above · or pay-as-you-go via API at the rate of whichever GPT-5.6 tier you select (Sol, Terra, or Luna) — Luna dropped 80% and Terra 20% on 30 July 2026',
    whenToUse: "If you're already paying for ChatGPT Plus, this is essentially a free Claude Code alternative. Worth trying before paying Claude Code API costs.",
    whenToAvoid: "When you need the highest-quality multi-file reasoning — Claude Code still leads on complex production codebases.",
  },
  {
    id: 'v0',
    name: 'v0 by Vercel',
    tagline: 'AI frontend platform — React components to full-stack sandbox',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f0f0',
    iconColor: '#1a1a1a',
    tags: ['UI generation', 'React', 'Next.js', 'One-click deploy'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 60,
    skillCoding: 30,
    skillColor: '#1a1a1a',
    howItWorks: 'Describe a UI in plain English and v0 generates production-ready React + Tailwind + shadcn/ui components instantly. Now available at v0.app (rebranded from v0.dev in late 2025). A major 2026 update added a built-in code editor, Git integration with branch creation and PRs from chat, a full-stack sandbox runtime, and database connectivity. One-click deploy to Vercel. Used by 6M+ developers and 80K+ active teams.',
    yourProject: null,
    pros: [
      'Cleanest React/Next.js component output of any AI tool',
      'February 2026 update added Git integration, code editor, and DB connectivity',
      'February 2026 update added Git panel, built-in code editor, and full-stack sandbox runtime',
      'One-click deploy to Vercel — no pipeline setup needed',
      'shadcn/ui + Tailwind output is production-grade',
    ],
    cons: [
      'Still frontend-first — backend, auth, and database rely on external tools despite new full-stack features',
      'Credit-based pricing: token usage scales with prompt complexity',
      'Tightly tied to Vercel ecosystem — less flexibility for other hosts',
    ],
    pricing: 'Free ($5 credits/mo) · Premium $20/mo · Team $30/user/mo · Business $100/user/mo · Enterprise custom',
    whenToUse: 'When you need the fastest path to a polished React UI. Pair with Supabase for backend and you have a full stack without writing much code.',
    whenToAvoid: "When you need Vue, Svelte, or vanilla JS output, or when you need a full-stack app with auth and database built in — Supabase + Claude Code is a better fit.",
  },
  {
    id: 'lovable',
    name: 'Lovable',
    tagline: 'Full-stack AI app builder — frontend, backend, database',
    workflow: null,
    workflowColor: null,
    iconBg: '#fdecea',
    iconColor: '#e05c4b',
    tags: ['Full-stack', 'No-code', 'Supabase built-in', 'Instant deploy'],
    tagColor: { bg: '#fdecea', text: '#922b21' },
    skillDesign: 40,
    skillCoding: 10,
    skillColor: '#e05c4b',
    howItWorks: 'Describe your app in plain English and Lovable generates the complete stack — React frontend, Supabase backend, authentication, and database — all wired together and deployed instantly. GitHub sync and custom domains included. Credit usage is complexity-based (not flat per message) — simple styling tweaks use ~0.5 credits while complex features use 1–2+. Unused credits now roll over month to month.',
    yourProject: null,
    pros: [
      'Generates full-stack apps — frontend + backend + auth in one prompt',
      'Supabase integration built in — no separate setup',
      'Credits now roll over month to month (added after user feedback)',
      'Unlimited collaborators on all plans — great for teams',
      'Commercial momentum is extraordinary: $500M ARR by June 2026, in talks to raise at $13.2B — double the $6.6B set in December 2025',
    ],
    cons: [
      'Pricing has been restructured more than once — current tiers are Pro and Business, not the older Starter/Launch/Scale names',
      'Published sources disagree on what is per-seat versus shared — check the pricing page before budgeting for a team',
      'Complex apps and debugging still burn credits fast',
      'Less control than a local codebase for complex custom logic',
    ],
    pricing: 'Free (5 credits/day, 30/mo ceiling) · Pro $25/mo (100 credits) · Business from $50/seat/mo (adds role-based access, centralised billing, team dashboards) · Enterprise custom — ~20% off annual; credits roll over; complexity-based usage',
    whenToUse: 'When you need a working full-stack app fast — MVPs, client portals, internal tools — especially for non-technical team members who can\'t use Claude Code or Cursor.',
    whenToAvoid: 'When you need precise control over your codebase, complex custom backend logic, or are already comfortable with the Claude Code + Vercel + Supabase workflow.',
  },
  {
    id: 'framer',
    name: 'Framer',
    tagline: 'Visual website builder with AI layout generation',
    workflow: null,
    workflowColor: null,
    iconBg: '#f5f0ff',
    iconColor: '#6b21a8',
    tags: ['Visual design', 'AI layouts', 'CMS', 'Instant publish'],
    tagColor: { bg: '#f5f0ff', text: '#5b21b6' },
    skillDesign: 85,
    skillCoding: 15,
    skillColor: '#7c3aed',
    howItWorks: 'A Figma-like canvas that publishes directly as a live website — no developer handoff needed. Describe a layout in plain English and AI generates a full responsive page instantly. Built-in CMS, hosting, SEO, and analytics. Trusted by 500,000+ designers including teams at Miro and Perplexity. Best for landing pages, portfolios, and marketing sites where visual quality matters most.',
    yourProject: null,
    pros: [
      'Design and publish in the same tool — no handoff to developers',
      'AI generates full page layouts from text prompts',
      'Built-in CMS, hosting, analytics, and custom domains',
      'Best-in-class animations and micro-interactions without code',
    ],
    cons: [
      'Steep learning curve coming from Figma — different mental model',
      'Per-site pricing adds up if running multiple projects',
      'Not ideal for complex content-heavy sites or large blogs',
      'Extra editors can get expensive on higher plans',
    ],
    pricing: 'Free · Mini $5/mo · Basic $15/mo · Pro $30/mo · Scale and custom pricing for teams',
    whenToUse: 'When you want a polished, design-forward website published fast without a developer. Great for landing pages, portfolios, and marketing sites where visual quality matters most.',
    whenToAvoid: 'When you need complex web app functionality, user auth, or a database — use Lovable or the Claude Code + Supabase workflow instead.',
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    tagline: 'Browser-based full-stack AI app builder by StackBlitz',
    workflow: null,
    workflowColor: null,
    iconBg: '#fff8e8',
    iconColor: '#b45309',
    tags: ['Full-stack', 'Browser-based', 'No install', 'React/Vite'],
    tagColor: { bg: '#fff8e8', text: '#92400e' },
    skillDesign: 35,
    skillCoding: 15,
    skillColor: '#d97706',
    howItWorks: 'Describe an app in plain English and Bolt generates a full React + Tailwind frontend with backend, database, auth, and hosting — all running in your browser via WebContainers (no local install needed). Bolt Cloud, shipped with V2, provides databases, auth, file storage, edge functions, analytics, and hosting: publishing puts the app on a Bolt subdomain immediately, with custom domains and automatic SSL on paid plans. In May 2026 StackBlitz partnered with Microsoft, adding Azure-native deployment, enterprise security and compliance, Teams and M365 Copilot integration, and Microsoft Marketplace procurement alongside AWS. Token pricing: free plan gets 1M tokens/month, Pro 10M. 2026 additions include Figma import, AI image editing, and Team Templates.',
    yourProject: null,
    pros: [
      'Zero install — runs entirely in the browser via WebContainers',
      'Bolt Cloud covers database, auth, storage, edge functions, and hosting — no separate backend to wire up',
      'One-click publish with custom domains and free SSL on paid plans',
      'Microsoft partnership adds Azure deployment and Marketplace procurement — meaningful if you buy through Azure or AWS',
      'Figma import — drop designs directly into chat',
      'Token rollover — unused tokens carry to next month on paid plans',
    ],
    cons: [
      'Token burn is project-size-dependent — Bolt syncs your whole codebase per message',
      'Free plan has 300K daily token limit — medium projects exhaust it quickly',
      'Per-member Teams pricing — compare carefully vs. Lovable for team use',
      'Agent churn: the V1 agent is retired for new projects and remaining V1 projects switch to the Claude agent default in August 2026',
    ],
    pricing: 'Free (1M tokens/mo, 300K/day) · Pro $25/mo (10M tokens) · Teams $30/member/mo · Enterprise custom — 10% annual discount available',
    whenToUse: 'When you want Lovable-style full-stack generation. Good for solo builders who want a generous token allowance and Figma import.',
    whenToAvoid: 'When you need the tightest frontend design polish (Lovable edges it out) or when building enterprise-grade apps where security and compliance are critical.',
  },
  {
    id: 'aistudio',
    name: 'Google AI Studio',
    tagline: 'Free browser IDE for prototyping with Gemini models',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8f4fb',
    iconColor: '#1a73e8',
    tags: ['Prompt IDE', 'API keygen', 'Vibe coding', 'Multimodal'],
    tagColor: { bg: '#e8f4fb', text: '#0c447c' },
    skillDesign: 25,
    skillCoding: 35,
    skillColor: '#1a73e8',
    howItWorks: "A free browser-based IDE for experimenting with Google's Gemini models. Test prompts, build app prototypes, generate API keys, and export working code — all without installing anything. Build mode is now powered by the Antigravity Agent and deploys full-stack apps (React or Angular frontend, Node.js backend) to managed Cloud Run containers, with Firebase provisioned automatically and secrets injected server-side. Since I/O in May 2026 it also builds native Android apps in Kotlin and Jetpack Compose with no SDK or local setup. As of April 1, 2026, Google enforced mandatory spending caps by tier and restricted Pro models behind a paywall on the free tier (free now Flash-only).",
    yourProject: null,
    pros: [
      'Completely free for Flash models — no credit card for basic use',
      'Build mode deploys to Cloud Run in one click, with secrets managed server-side rather than hardcoded in frontend code',
      'Only tool here with a prompt-to-native-Android path',
      'Multimodal — test text, image, video, and audio prompts in one place',
      'Spend caps added — no surprise runaway bills',
    ],
    cons: [
      'Stability is the real risk: the March 2026 full-stack overhaul brought backend state conflicts, "Internal Error Occurred" on migration, infinite thinking loops, and preview crashes, and reports persist on Google\'s developer forum',
      'Build mode has been reported to lose original functionality when refactoring larger existing files',
      'April 2026: free tier now Flash models only — Gemini Pro requires paid billing',
      'Free tier data may be used by Google for model training',
      'Platform churn — Build mode has already been re-based onto the Antigravity Agent since launch',
    ],
    pricing: 'Free (browser IDE, Flash models only as of April 2026) · API free tier → pay-as-you-go · Flash-Lite from $0.10/MTok; 3.1 Pro from ~$1.25/MTok input',
    whenToUse: 'When you want to prototype with Gemini models for free, generate an API key, or test multimodal prompts (text + image + video) without any setup or cost.',
    whenToAvoid: 'When you need the best reasoning or writing quality — Claude.ai and ChatGPT have an edge. Also avoid the free tier for sensitive business data as Google may use it for training.',
  },
  {
    id: 'windsurf',
    name: 'Devin Desktop (formerly Windsurf)',
    tagline: 'AI-native code editor with agentic Cascade AI — rebranded June 2026',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f6ff',
    iconColor: '#378add',
    tags: ['AI editor', 'Agentic coding', 'Codebase-aware'],
    tagColor: { bg: '#eef5ff', text: '#0c4484' },
    skillDesign: 15,
    skillCoding: 65,
    skillColor: '#378add',
    howItWorks: 'A full code editor built from scratch around AI — not a plugin or fork. Its core feature is Cascade, an AI that understands your entire project at once, edits across multiple files, runs terminal commands, and debugs automatically. Originally built by Codeium, acquired by Cognition AI for ~$250M in 2025, and rebranded as Devin Desktop on 2 June 2026 — windsurf.com now redirects to devin.ai. Pro includes SWE-1.5, Cognition\'s own coding model, plus cloud sessions for background work.',
    yourProject: null,
    pros: [
      'Cascade understands your whole codebase — not just the open file',
      'Edits multiple files at once autonomously',
      'Cloud sessions run background work without tying up your machine',
      'Free tier is genuinely useful — not just a trial',
    ],
    cons: [
      'High learning curve for non-developers',
      'Two renames and a pricing overhaul inside a year — March 2026 replaced credits with daily/weekly quotas and raised Pro from $15 to $20',
      'Now sits under the Devin brand, so the editor competes for roadmap attention with Cognition\'s autonomous agent',
      'Overkill if Claude Code already meets your needs',
    ],
    pricing: 'Free (limited daily quota) · Pro $20/mo · Max $200/mo · Teams $40/user/mo · Enterprise custom — daily and weekly quotas replaced the old credit system in March 2026',
    whenToUse: 'If you want a Cursor alternative with stronger agentic capabilities baked into the editor itself. Worth trying on the free tier before committing.',
    whenToAvoid: 'If you are not a developer or do not work inside a code editor day-to-day — tools like Lovable or Bolt will serve you better. Also worth weighing the brand churn if you want something stable to build a habit around.',
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    tagline: 'The world\'s most widely used AI coding assistant',
    workflow: null,
    workflowColor: null,
    iconBg: '#eaf3de',
    iconColor: '#3b6d11',
    tags: ['Code completion', 'Chat', 'Agent mode', 'Multi-model', 'IDE plugin'],
    tagColor: { bg: '#eaf3de', text: '#2a5a0a' },
    skillDesign: 10,
    skillCoding: 55,
    skillColor: '#34c759',
    howItWorks: 'A plugin that sits inside your existing editor — VS Code, JetBrains, Visual Studio, Neovim, Xcode, Eclipse — suggesting code as you type, with a chat mode and an agent mode for multi-step edits. The most widely adopted AI coding tool in the world with 20M+ users. On 1 June 2026 it moved from Premium Request Units to usage-based GitHub AI Credits tied to actual token consumption.',
    yourProject: null,
    pros: [
      '20M+ users — biggest community and most resources of any AI coding tool',
      'Widest IDE support of any tool here — VS Code, JetBrains, Xcode, Eclipse, Neovim',
      'Inline completions and next-edit suggestions are free on all paid plans and consume no credits',
      'Multi-model chat — pick the model that suits the task',
      'Free tier available with no credit card',
    ],
    cons: [
      'June 2026 switch to usage-based credits was contentious — base prices held, but token-heavy chat and agent work now bites',
      'Only chat, agent mode, code review, and Copilot CLI draw credits, so cost is harder to predict than a flat plan',
      'Plugin experience is less integrated than Cursor or a purpose-built AI editor',
    ],
    pricing: 'Free · Pro $10/mo (includes $10 AI Credits) · Pro+ $39/mo ($39 credits) · Max $100/mo · Business $19/user/mo · Enterprise $39/user/mo — 1 credit = $0.01; Business and Enterprise pool credits across seats',
    whenToUse: 'When you want AI in your IDE at the lowest possible cost, or you work across several editors. Free completions on paid plans make Pro good value if you mostly want autocomplete.',
    whenToAvoid: 'If you want a fully agentic experience — Claude Code, Cursor, or Devin Desktop act on your whole codebase far more autonomously.',
  },
]

export const openWeightModels = [
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    maker: 'Moonshot AI',
    rank: 'Strongest open model overall',
    accent: '#5856d6',
    accentBg: '#eeedfe',
    tagline: 'Frontier-class reasoning and agentic coding you can download.',
    specs: [
      { label: 'Parameters', value: '2.8T MoE (16 of 896 experts per token)' },
      { label: 'Context', value: '1M tokens' },
      { label: 'License', value: 'Modified MIT (Kimi K3 License)' },
      { label: 'Weights', value: 'Hugging Face — moonshotai/Kimi-K3, July 27 2026' },
      { label: 'API price', value: '$3 / $15 per 1M tokens (in / out)' },
    ],
    benchmarks: [
      { label: 'GPQA Diamond', value: '93.5%' },
      { label: "Humanity's Last Exam", value: '56%' },
      { label: 'Terminal-Bench 2.1', value: '88.3%' },
      { label: 'LiveBench Coding', value: '81.5' },
    ],
    strengths: 'Tops the open-weight leaderboards on reasoning, browsing and terminal use. Native vision, hybrid linear attention, and the best long-horizon agentic coding of any downloadable model.',
    tradeoffs: 'At 2.8T parameters it is realistically an API model — self-hosting means a rented multi-GPU node. The licence is modified, not plain MIT.',
  },
  {
    id: 'glm-5-2',
    name: 'GLM-5.2',
    maker: 'Z.ai (Zhipu)',
    rank: 'Best single-node model',
    accent: '#0b8f6a',
    accentBg: '#e8faf4',
    tagline: 'The practical pick — genuinely MIT, and it fits on one machine.',
    specs: [
      { label: 'Parameters', value: '753B sparse MoE (~40B active)' },
      { label: 'Context', value: '1M tokens (131K output)' },
      { label: 'License', value: 'MIT — no regional restrictions' },
      { label: 'Weights', value: 'Hugging Face, June 2026' },
      { label: 'API price', value: 'Roughly a sixth of comparable closed models' },
    ],
    benchmarks: [
      { label: 'GPQA Diamond', value: '91.2%' },
      { label: "Humanity's Last Exam", value: '54.7%' },
      { label: 'Single-node coding leader', value: '51.1' },
    ],
    strengths: 'Fully permissive MIT weights, 1M context kept affordable by its IndexShare sparse attention, and the strongest scores among models that fit a single inference node.',
    tradeoffs: 'Still trails Kimi K3 and DeepSeek V4 Pro on the hardest agentic coding benchmarks. "Single node" still means serious GPU hardware.',
  },
  {
    id: 'deepseek-v4',
    name: 'DeepSeek V4',
    maker: 'DeepSeek',
    rank: 'Best cost-to-performance',
    accent: '#c2410c',
    accentBg: '#fff1e8',
    tagline: 'Leads agentic coding on downloadable weights, at a fraction of the price.',
    specs: [
      { label: 'Parameters', value: 'V4 Pro — 1.6T MoE (49B active) · V4 Flash — 284B' },
      { label: 'Context', value: '1M tokens' },
      { label: 'License', value: 'MIT' },
      { label: 'Weights', value: 'Hugging Face — Pro and Flash both downloadable' },
      { label: 'API price', value: 'Pro $0.44 / $0.87 · Flash $0.14 / $0.28 per 1M' },
    ],
    benchmarks: [
      { label: 'SWE-bench Verified (Pro Max)', value: '80.6%' },
      { label: 'SWE-bench Verified (Flash)', value: '79.0%' },
    ],
    strengths: 'Highest SWE-bench Verified score of any model you can download, and the Flash variant gets within 2 points at a twentieth of the token cost. Plain MIT licence.',
    tradeoffs: 'Weaker than Kimi K3 on general reasoning and multimodal work. Pro is too large for practical self-hosting — Flash is the one you would actually run.',
  },
]

export const openWeightNote = 'Open-weight means the model files are published and you can download, self-host, fine-tune, and inspect them — as opposed to closed models like Claude or GPT that exist only behind an API. The gap to the closed frontier is now small; what remains is instruction-following polish and multimodal depth.'
