export const tools = [
  {
    id: 'figma',
    name: 'Figma / Figma Make',
    tagline: 'Design-to-code with AI generation',
    workflow: 2,
    workflowColor: '#ff2d55',
    iconBg: '#fff0f3',
    iconColor: '#ff2d55',
    tags: ['UI design', 'Prototyping', 'Design systems'],
    tagColor: { bg: '#fff0f3', text: '#c0185a' },
    skillDesign: 90,
    skillCoding: 25,
    skillColor: '#ff2d55',
    howItWorks: 'Figma is a browser-based design tool. Figma Make is its AI layer — describe a UI in natural language and it generates working React components or interactive prototypes directly inside Figma. Output can be exported as code.',
    yourProject: 'Guitar Practice Tracker — React + Tailwind, Apple-inspired design, 34 features including metronome, chord finder, recorder, and spaced repetition.',
    pros: [
      'No coding knowledge needed to get started',
      'Generates production-ready React + Tailwind code',
      'Instant visual feedback as you build',
      'Apple-quality design defaults out of the box',
    ],
    cons: [
      'Hosted on Figma\'s platform — less deploy control',
      'Harder to maintain long-term vs. a local codebase',
      'Complex logic can require manual code editing',
    ],
    pricing: 'Free tier available · Figma Make included in paid plans from $15/mo',
    whenToUse: 'When you have a clear visual idea and want to go from concept to working UI fast — especially for design-heavy apps where aesthetics matter as much as functionality.',
    whenToAvoid: 'When you need deep backend logic, complex state management, or a project you\'ll iterate on heavily over time.',
  },
  {
    id: 'replit',
    name: 'Replit',
    tagline: 'Browser-based coding + AI agent',
    workflow: null,
    workflowColor: null,
    iconBg: '#e8faf4',
    iconColor: '#1d9e75',
    tags: ['Quick prototypes', 'No-setup coding', 'Instant deploy'],
    tagColor: { bg: '#e8faf4', text: '#0a6b4a' },
    skillDesign: 30,
    skillCoding: 35,
    skillColor: '#1d9e75',
    howItWorks: 'A cloud IDE that runs entirely in the browser — no local setup needed. Replit Agent lets you describe an app in plain English; it scaffolds, codes, debugs, and deploys for you. Hosts the app on Replit\'s own infrastructure automatically.',
    yourProject: null,
    pros: [
      'Zero local setup — works on any device with a browser',
      'Agent handles scaffolding, debugging, and deploy in one place',
      'Great for quick experiments and sharing prototypes',
      'Supports dozens of languages and frameworks',
    ],
    cons: [
      'Less control than a local dev environment',
      'Hosted on Replit infrastructure — not your own domain by default',
      'Can get expensive for always-on apps',
    ],
    pricing: 'Free tier available · Replit Core from $25/mo · Agent usage billed separately',
    whenToUse: 'When you want to spin up a working app fast without touching your local machine — demos, quick experiments, or sharing something with a non-technical collaborator.',
    whenToAvoid: 'When you need production-grade reliability, custom domains, or a codebase you\'ll maintain long-term with version control.',
  },
  {
    id: 'claude',
    name: 'Claude / Claude Code',
    tagline: 'AI pair programmer + agentic CLI coder',
    workflow: 1,
    workflowColor: '#007aff',
    iconBg: '#f0f4ff',
    iconColor: '#5856d6',
    tags: ['Code generation', 'Debugging', 'Refactoring'],
    tagColor: { bg: '#f0f0ff', text: '#3634a3' },
    skillDesign: 40,
    skillCoding: 50,
    skillColor: '#5856d6',
    howItWorks: 'Claude.ai is a chat interface for code generation, explanation, and review. Claude Code is a terminal agent that reads your codebase, plans changes, runs commands, and edits files autonomously — working alongside VS Code and your local tools.',
    yourProject: 'AI Updates dashboard (ai-updates-ten.vercel.app) — React/Vite app with on-demand RSS summarization, Apple-inspired design, mobile responsive.',
    pros: [
      'Understands full codebase context, not just snippets',
      'Claude Code edits files directly — no copy/paste',
      'Excellent at debugging complex multi-file issues',
      'Tight integration with your existing local workflow',
    ],
    cons: [
      'Requires a local dev environment (VS Code, Node, etc.)',
      'Claude Code uses API credits — costs add up on large projects',
      'Less visual/design-oriented than Figma Make',
    ],
    pricing: 'Claude.ai Pro $20/mo · Claude Code billed per API token usage',
    whenToUse: 'Your primary workflow. Best for projects you own end-to-end — building, debugging, refactoring, and deploying via GitHub + Vercel.',
    whenToAvoid: 'When you just need a quick throwaway prototype and don\'t want to set up a full local environment.',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'AI-native code editor (VS Code fork)',
    workflow: null,
    workflowColor: null,
    iconBg: '#f0f6ff',
    iconColor: '#378add',
    tags: ['Editor-centric', 'Codebase Q&A', 'Inline edits'],
    tagColor: { bg: '#eef5ff', text: '#0c4484' },
    skillDesign: 20,
    skillCoding: 60,
    skillColor: '#378add',
    howItWorks: 'A fork of VS Code with AI deeply embedded. Understands your entire codebase via embeddings, lets you chat with your repo, auto-completes multi-line edits, and applies AI suggestions inline. Uses Claude, GPT-4, and other models under the hood.',
    yourProject: null,
    pros: [
      'AI lives inside the editor — no context switching',
      'Codebase-aware: understands your whole project, not just open files',
      'Powerful tab autocomplete for multi-line edits',
      'Familiar VS Code interface — near-zero learning curve',
    ],
    cons: [
      'Another subscription on top of Claude/GitHub/Vercel',
      'Less capable as an autonomous agent vs. Claude Code',
      'Model quality depends on which underlying AI you select',
    ],
    pricing: 'Free tier (limited) · Pro $20/mo · Business $40/user/mo',
    whenToUse: 'If you want AI more deeply embedded in your editor experience and prefer typing in context over running a separate terminal agent.',
    whenToAvoid: 'If Claude Code already covers your needs — adding Cursor is largely redundant unless you specifically want the inline editor experience.',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    tagline: 'Deployment + hosting platform',
    workflow: 1,
    workflowColor: '#1d1d1f',
    iconBg: '#f5f5f7',
    iconColor: '#1d1d1f',
    tags: ['Deployment', 'Hosting', 'Preview URLs', 'Serverless'],
    tagColor: { bg: '#f0f0f0', text: '#3a3a3c' },
    skillDesign: 10,
    skillCoding: 30,
    skillColor: '#6e6e73',
    howItWorks: 'Connect a GitHub repo and Vercel auto-deploys every push. Handles CDN, serverless functions, environment variables, and preview URLs per branch. Optimized for React/Next.js but works with Vite, Svelte, and more.',
    yourProject: 'Hosts the AI Updates dashboard at ai-updates-ten.vercel.app — auto-deploys on every GitHub push.',
    pros: [
      'Zero-config deploys — push to GitHub, it\'s live',
      'Preview URLs for every branch — great for testing before merging',
      'Global CDN built in — fast everywhere',
      'Serverless functions for lightweight backend needs',
    ],
    cons: [
      'Not a coding tool — purely for deploy/host',
      'Free tier has usage limits; costs scale with traffic',
      'Vendor lock-in if you use Vercel-specific features heavily',
    ],
    pricing: 'Free hobby tier · Pro $20/mo · Enterprise custom pricing',
    whenToUse: 'Every time. This is the final step of Workflow 1 — the pipe that takes your GitHub code and puts it live on the internet automatically.',
    whenToAvoid: 'No real reason to avoid it for your use case. For very heavy backend workloads you\'d eventually move to a dedicated server, but that\'s far off.',
  },
  {
    id: 'github',
    name: 'GitHub',
    tagline: 'Version control + collaboration + CI/CD',
    workflow: 1,
    workflowColor: '#34c759',
    iconBg: '#eaf3de',
    iconColor: '#3b6d11',
    tags: ['Version control', 'History & rollback', 'Collaboration'],
    tagColor: { bg: '#eaf3de', text: '#2a5a0a' },
    skillDesign: 5,
    skillCoding: 40,
    skillColor: '#34c759',
    howItWorks: 'Cloud-hosted Git. Stores your code, tracks every change, and lets you roll back or branch freely. GitHub Actions can automate tests or builds. Vercel watches your repos and deploys on push. GitHub Copilot adds inline AI suggestions in editors.',
    yourProject: 'Source of truth for the AI Updates dashboard — every Claude Code edit gets committed and pushed here, triggering a Vercel deploy.',
    pros: [
      'Safety net for everything — roll back any mistake',
      'Branching lets you experiment without breaking production',
      'Vercel integration means deploy is automatic on push',
      'Free for public and private repos',
    ],
    cons: [
      'Git concepts (branches, commits, merge conflicts) have a learning curve',
      'Not a coding or deploy tool on its own — needs the rest of the stack',
    ],
    pricing: 'Free for individuals (unlimited private repos) · Teams $4/user/mo',
    whenToUse: 'Always — every project should be on GitHub from day one. It\'s the connective tissue between Claude Code and Vercel.',
    whenToAvoid: 'There\'s no good reason to avoid GitHub in your workflow. It\'s free and essential.',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    tagline: 'Open-source backend as a service',
    workflow: 2,
    workflowColor: '#1d9e75',
    iconBg: '#e8faf4',
    iconColor: '#1d9e75',
    tags: ['Auth & logins', 'Cloud database', 'Multi-user apps', 'Real-time sync'],
    tagColor: { bg: '#e8faf4', text: '#0a6b4a' },
    skillDesign: 5,
    skillCoding: 45,
    skillColor: '#1d9e75',
    howItWorks: 'Supabase gives you a full Postgres database, user authentication, file storage, and edge functions — all through a simple dashboard and JavaScript SDK. Connect it to your frontend and it handles backend plumbing: storing data, managing logins, and syncing across users.',
    yourProject: 'Powers the Guitar Practice Tracker backend — Postgres KV store, Hono edge functions, user auth with signup/login, per-user data storage, and migration from anonymous to authenticated accounts.',
    pros: [
      'Full Postgres database — far more powerful than simple key-value stores',
      'Auth system built in — email/password, OAuth, magic links out of the box',
      'Works with any frontend framework (React, Vue, vanilla JS)',
      'Open source — can self-host if needed',
      'Generous free tier for small projects',
    ],
    cons: [
      'More setup than a purely frontend-only app',
      'SQL/database concepts help but aren\'t required',
      'Edge functions require some backend comfort to configure',
    ],
    pricing: 'Free tier (2 projects, 500MB DB) · Pro $25/mo per project',
    whenToUse: 'Any time your app needs user accounts, data that persists across sessions, or multi-user support. Could be added to Workflow 1 (Claude Code + Vercel) just as easily as Workflow 2.',
    whenToAvoid: 'For purely static apps or single-user tools where data only lives in the browser — overkill if you don\'t need a backend.',
  },
]

export const workflows = [
  {
    id: 1,
    label: 'Workflow 1 — current stack',
    subtitle: 'AI Updates dashboard · local dev · GitHub deploy',
    color: '#007aff',
    project: 'AI Updates dashboard (ai-updates-ten.vercel.app) — React/Vite app with on-demand RSS summarization, Apple-inspired design, mobile responsive.',
    steps: [
      { name: 'Claude.ai', role: 'Ideate & generate', iconBg: '#f0f4ff', icon: 'claude' },
      { name: 'Claude Code', role: 'Edit & build locally', iconBg: '#f0f4ff', icon: 'claudecode' },
      { name: 'GitHub', role: 'Commit & version', iconBg: '#eaf3de', icon: 'github' },
      { name: 'Vercel', role: 'Deploy & host', iconBg: '#f5f5f7', icon: 'vercel' },
    ],
  },
  {
    id: 2,
    label: 'Workflow 2 — Figma Make + Supabase',
    subtitle: 'Guitar Practice Tracker · browser-based · cloud backend',
    color: '#ff2d55',
    project: 'Guitar Practice Tracker — React + Tailwind, Apple-inspired design, 34 features including metronome, chord finder, recorder, and spaced repetition.',
    steps: [
      { name: 'Figma Make', role: 'Design & build UI', iconBg: '#fff0f3', icon: 'figma' },
      { name: 'React + Tailwind', role: 'Generated code', iconBg: '#e8faf4', icon: 'react' },
      { name: 'Supabase', role: 'Auth & cloud data', iconBg: '#e8faf4', icon: 'supabase' },
      { name: 'Figma hosted', role: 'Live in browser', iconBg: '#fff0f3', icon: 'web' },
    ],
  },
]
